version: 2.1

executors:
  defaults_typescript:
    docker:
      - image: circleci/node:10.13.0
      - image: circleci/postgres:9.6-alpine-ram
        environment:
          - POSTGRES_DB=seed
          - POSTGRES_USER=seed
          - POSTGRES_PASSWORD=Ge0rgesMoustaki
          - PGPORT=5434

commands:
  yarn-install:
    steps:
      - checkout
      - attach_workspace:
          at: ~/nestjs-admin
      - restore_cache:
          key: node-modules-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install front dependencies
          command: yarn
      - run:
          name: Install bundle size
          command: yarn add bundlesize --save-dev
      - save_cache:
          key: node-modules-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/nestjs-admin
          paths:
            - node_modules
            - .env

  yarn-tests:
    steps:
      - checkout
      - attach_workspace:
          at: ~/nestjs-admin
      - run:
          name: Unit test with coverage
          command: yarn test:coverage
      - store_artifacts:
          path: coverage
      - run:
          name: Run Typescript checker
          command: yarn tsc

  yarn-linter:
    steps:
      - checkout
      - attach_workspace:
          at: ~/nestjs-admin
      - run:
          name: Run linter
          command: yarn lint
      - store_artifacts:
          path: coverage

jobs:
  yarn-install-back:
    executor: defaults_typescript
    working_directory: ~/nestjs-admin
    steps:
      - yarn-install

  nest-tests:
    executor: defaults_typescript
    working_directory: ~/nestjs-admin
    environment:
      NODE_ENV: test
    steps:
      - yarn-tests

  nest-linter:
    executor: defaults_typescript
    working_directory: ~/nestjs-admin
    environment:
      NODE_ENV: prod
    steps:
      - yarn-linter

workflows:
  version: 2
  stack:
    jobs:
      - yarn-install-back
      - nest-tests:
          requires:
            - yarn-install-back
      - nest-linter:
          requires:
            - yarn-install-back
